### ISSUE TITLE
Could you please update README?

### ISSUE THREAD

**Issue by JavaHelper** [sivaprasadreddy/springboot-rest-api-design#1]
Your tutorials are very good someone can easily learn through it. However I'm really finding difficulties in running the app as there are no steps being given how to run it. Please do the needful.

Could you also please create few more test cases which covers all functionality?

**Comment by sivaprasadreddy** [comment]
Planning to write a tutorial about designing REST API using SpringBoot and this repo is the code backing that tutorial. I have just added some basic instruction in README file about how to run the application.

If you need any further details please let me know.

**Comment by JavaHelper** [comment]
Thank you. Yes, I will let you know if I encounter any issues. It would be great if you add AngularJS support as well. All the best.
